<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <RootNamespace>LAE</RootNamespace>
    </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DemoApp\**" />
    <Compile Remove="TestRunner\**" />
    <Compile Remove="UI\**" />
    <None Remove="DemoApp\**" />
    <None Remove="TestRunner\**" />
    <None Remove="UI\**" />
    <Page Remove="DemoApp\**" />
    <Page Remove="UI\**" />
    <ApplicationDefinition Remove="UI\**" />
  </ItemGroup>

</Project>
